### ISSUE TITLE
Video swagger mismatch

### ISSUE THREAD

**Issue by meapistol** [mrosseel/bisq-api#1]
In the video tutorial at 2:37 or so there are instructions of base_currency and counter_currency.
However in the swagger I have it says market_pair instead. I am not sure how the input should be.
It is not clear from bisq-api-examples either.
The video should be a bit updated with this and I would appreciate an example, since I am a noobie.

**Comment by mrosseel** [comment]
yes that's possible, the video was made during development and is just meant to give a high-level idea of what the api is about. I'll see if I can add better documentation to that swagger method.
To answer your question, the market_pair could be xmr_btc. There are also shell scripts which show some example calls, in the /support directory

**Comment by mrosseel** [comment]
closing this as the video is now wildly out of date.
New issues regarding the current swagger docs are still welcome of course!
