### ISSUE TITLE
Write integration tests

### ISSUE THREAD

**Issue by mrosseel** [mrosseel/bisq-api#10]
Minimally, there needs to be a way to test that simple scenarios still work when there is a new bisq release without manually retesting.

* tester starts 2 api instances on port 8080 and 8081
* integration test runs, fires api calls to both ports
* integration test checks if responses are as expected

Questions:
* what to do with accounts (can't be created via api, id's change), see #18 
* junit or mailman?

**Comment by blabno** [comment]
Done
