### ISSUE TITLE
Migrate build to Gradle

### ISSUE THREAD

**Issue by blabno** [mrosseel/bisq-api#102]
As a developer, I want to use Gradle to build the project instead of Maven.

Currently, the shading jar does not work and since the API might get incorporated into desktop we probably don't need that shading yet.

Failsafe plugin is configured in `integration` profile so that integration tests are not executed by default.

Current Maven build does not rely on any magic.

It is important to also migrate `startApi.sh`, a startup script for docker container.

**Comment by blabno** [comment]
`gradle init` generates simple `build.gradle` file that works, but I don't know how to exclude integration tests from default build. Also I'm not sure how the `startApi.sh` should be modified for `dev` mode to work with gradle.

Ideally docker image for production should not require compilation and everything should be ready there just to invoke `java -jar ....`.

**Comment by mrosseel** [comment]
hi @blabno could this issues be closed? Gradle build is working, if there are some remaining problems these could be documented in another issues.

**Comment by blabno** [comment]
We can close it. All is working fine.
