### ISSUE TITLE
Getting started with the API on windows step-by-step

### ISSUE THREAD

**Issue by menkaur** [mrosseel/bisq-api#109]
I want to start bisq and specify a port at which it will listen to my api requests.

I've tried running bidq with following batch:

```
set BISQ_API_PORT =8000
set BISQ_API_HOST=localhost
bisq
```

however, when I go to http://localhost:8000 , I get `localhost refused to connect.`

Another command I've tried was:

``bisq`  -p 8080:8080 -p 9999:9999 bisq/api`

Yet, again, same error, on port 8080

I'm obviously doing something wrong, but I'm not quite sure what.

How do I start Bisq with api enabled?

**Comment by blabno** [comment]
You must checkout The source code https://github.com/mrosseel/bisq-api and run that code. Also read full readme of that project

**Comment by menkaur** [comment]
no, I just run it from command prompt

**Comment by blabno** [comment]
Can you paste the whole command?

**Comment by menkaur** [comment]
First command I tried was this one:

```
set BISQ_API_PORT =8000
set BISQ_API_HOST=localhost
bisq
```

second one was this:

`bisq  -p 8080:8080 -p 9999:9999 bisq/api
`

**Comment by blabno** [comment]
Readme says to do this:

`./gradlew run --args ' --appName Bisq-api'`

**Comment by blabno** [comment]
Make sure to fetch latest changes.

**Comment by menkaur** [comment]
Is there any way the program can be started with api port open without using gradle?

**Comment by blabno** [comment]
No, cause it's not released yet and thus you have to build from the source code. If you're not able to do that I can build it for you but once I get back from holiday, which will be on Monday.

**Comment by menkaur** [comment]
Ah. Now I see what the issue is

**Comment by menkaur** [comment]
Got it working, thank you
