### ISSUE TITLE
Response reports time-out, but offer created

### ISSUE THREAD

**Issue by Quenos** [mrosseel/bisq-api#12]
When using the api to create a buy offer, a time-out was reported. The offer, however, available.
Request URL

http://localhost:8080/api/v1/offer_make?payment_account_id=e366bb93-e6e9-49df-a282-80b2c2bd9759&direction=BUY&price_type=PERCENTAGE&market_pair=btc_eur&percentage_from_market_price=0.01&fixed_price=0&amount=1000000&min_amount=1000000

Response Body
{
  "code": 500,
  "message": "Timeout exceeded, check the logs for errors."
}

But:
Request URL

http://localhost:8080/api/v1/offer_list?market=all&status=all&whose=all&start=0&end=10&limit=100

Response Body

[
  {
    "offer_id": "87598917-5eb0-4370-a60a-d2a6332eb6fb",
    "direction": "BUY",
    "state": "UNKNOWN",
    "created": 1516295951508,
    "arbitrators": [
      "localhost:9222"
    ],
    "offerer": "localhost:2003",
    "btc_amount": "0.01",
    "min_btc_amount": "0.01",
    "other_amount": "9734.7393",
    "other_currency": "EUR",
    "price_detail": {
      "use_market_price": true,
      "market_price_margin": 0.01
    }
  }
]

**Comment by citkane** [comment]
I cannot reproduce the timeout error (v0.6.3 from master for both seednode and api) on my regtest environment:
```
http://localhost:3123/api/v1/offer_make?payment_account_id=611cc6c8-4e56-4aa2-8806-26a16ab75e99&direction=BUY&price_type=PERCENTAGE&market_pair=btc_eur&percentage_from_market_price=0.01&fixed_price=0&amount=1000000&min_amount=1000000
```
returns:true

@Quenos  - is this happening for you every time, or was it a "one time" event?
Are you running regtest, testnet or mainnet?

I updated the [step by step regtest guide](https://github.com/mrosseel/bisq-api/issues/4) to reflect that master branch for bisq-network/exchange is working again.

**Comment by Quenos** [comment]
Happened with all make transactions and aftercouple of restarts. 
After following the step by step guide setting up the network problems went away. 

Issue can be closed

**Comment by mrosseel** [comment]
Timeout is currently 5 seconds, I've increased it to 10 seconds (not only due to this report).
Let me know if it happens again.
