### ISSUE TITLE
Restrict API access to localhost:<port> as default.

### ISSUE THREAD

**Issue by citkane** [mrosseel/bisq-api#17]
If the API is started on a server with a public IP, the API endpoint port is exposed to public access. 

A secure default could be to restrict the http server of the API to allow only requests from `localhost:<api port>` . Optionally allow startup argument to allow remote access from other domains or IP's.

**Comment by mrosseel** [comment]
now by default only accessible by localhost, to open it you have to edit bisq-api.yml
No cmd line arguments added for now, to be seen what's most convenient for users/packagers
