### ISSUE TITLE
Help with setting up dev environment

### ISSUE THREAD

**Issue by citkane** [mrosseel/bisq-api#2]
Hi,
I am doing some exploration and testing, but would appreciate help with setting up the dev environment for regtest with two instances.

I have managed to compile with Maven and get a regtest GUI instance running, but got stuck with trying to set up a seednode using the instructions here: https://github.com/bisq-network/exchange/wiki/How-to-use-bisq-with-regtest-%28advanced%29

These instructions appear to be outdated, or not relevant to API version. I cannot find the linked "SeedNode.jar" as it just points to the latest release of core, where the file is not listed.

Also, could you explain how to fund the regtest Btc wallets and create a regtest arbitrator.

Thanks in advance, I look forward to testing the API.

**Comment by mrosseel** [comment]
there is indeed no Seednode.jar to download, but if you have a checkout of the bisq-excange you can start the SeedNode from there

**Comment by meapistol** [comment]
citkane. I have similar problems. Maybe you can explain in some detail when you manage to set up the dev environment. Somebody (me?) shoud try to write a wiki how to use the api.

**Comment by citkane** [comment]
Thanks @mrosseel 

@meapistol , I am one step closer. As mrosseel says, you need to clone the main bisq-network from here: https://github.com/bisq-network/exchange and follow the compile instructions here: https://github.com/bisq-network/exchange/blob/master/doc/build.md

This will give you the SeedNode.jar file at `<bisq-network-installdir>/seednode/target/SeedNode.jar`

After that, you can do (on Linux):
```
cd <bisq-network-dir>

java -jar seednode/target/SeedNode.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:2002 --nodePort=2002 --appName=bisq_seed_node_localhost_2002
```
Open new terminal:

```
cd <bisq-api-dir>

BISQ_API_PORT=2223 mvn exec:java -Dexec.mainClass="io.bisq.api.app.BisqApiWithUIMain" -Dexec.args="--baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost localhost --nodePort 2222 --useLocalhost true --appName Bisq-Regtest-Bob"
```
Open new terminal:

```
cd <bisq-api-dir>

BISQ_API_PORT=3334 mvn exec:java -Dexec.mainClass="io.bisq.api.app.BisqApiWithUIMain" -Dexec.args="--baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost localhost --nodePort 3333 --useLocalhost true --appName Bisq-Regtest-Alice"
```

I am now looking at how to configure a regtest arbitrator and fund the wallets. However, something nasty appears to be happening for me:

The steps above gives me 2 GUI instances and it is stable for a minute or two before a fatal crash. There are no console logs, my laptop just turns off (not hang, just completely off) suddenly and instantly. The last log messages on file are:

For seednode: 
[bisq.log](https://github.com/mrosseel/bisq-api/files/1567834/bisq.log)

`Dec-18 11:37:04.334 [SeedNodeMain] INFO  i.b.n.p.p.g.RequestDataHandler: We send a PreliminaryGetDataRequest to peer localhost:3002.` 
`Dec-18 11:37:04.342 [SeedNodeMain] INFO  i.b.c.a.AppSetupWithP2P: onNoSeedNodeAvailable`

For clients:
[bisq.log](https://github.com/mrosseel/bisq-api/files/1567836/bisq.log)

`Dec-18 11:32:25.692 [JavaFX Application Thread] INFO  i.b.c.u.Utilities: System info: os.name=Linux; os.version=4.13.0-19-generic; os.arch=amd64; sun.arch.data.model=64; JRE=1.8.0_151-b12 (Oracle Corporation); JVM=25.151-b12 (Java HotSpot(TM) 64-Bit Server VM)`

For kernel:
[kern.log](https://github.com/mrosseel/bisq-api/files/1567820/kern.log)

Nothing obvious in kern.log (crash between timestamps Dec 18 11:26:32 and Dec 18 11:37:36)
Os = Ubuntu 17.10 64bit, any ideas for debugging appreciated!

Other observation:

The 'initializing' indicator (bottom left of the GUI) never completes (see screenshot):
 
![bisq-alice](https://user-images.githubusercontent.com/998947/34106553-8d659884-e3f0-11e7-9bad-cbd51a07144d.jpg)

Maybe this is related to log message from seednode `We send a PreliminaryGetDataRequest to peer localhost:3002`, but I started seednode on port 2002 `--useLocalhost=true --myAddress=localhost:2002 --nodePort=2002`

Everything else seems to be working as can be seen on the screenshot, the client instance is seeing the peer and seednode.

**Comment by mrosseel** [comment]
Need to look at it in more detail, but can already answer one thing: the
indicator finales as soon as you mine one regtest block. Go to the bitcoin
debug console and type 'generate 1'

**Comment by citkane** [comment]
Ok - I am slowly becoming enlightened. What I had failed to realise is that I needed to install and run bitcoin-coin in regtest mode as well. (this is the bitcoin-core app, nothing to do with Bisq, found here: https://bitcoin.org/en/bitcoin-core/

After this, all my instances are running without crash, all are finilizing and connecting to the regtest network.

There is one more step I am stuck on, after which I will write a detailed guide: Registering a regtest arbitrator.

I followed the guide here: https://github.com/bisq-network/exchange/wiki/4.2.1.-How-to-use-Bisq-with-regtest-(advanced) and adjusted  [DevEnv.java](https://github.com/bisq-network/exchange/blob/master/common/src/main/java/io/bisq/common/app/DevEnv.java) appropriately, recompiled and ran `java -jar gui/target/shaded.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:4444 --nodePort=4444 --appName=Bisq-Regtest-Arbitrator`. 

This worked fine and I was able to register an arbitrator.

However - DevEnv.java is not available in the API repo, and the GUI instances running from the API version do not recognise the arbitraor. Re-starting "appName=Bisq-Regtest-Arbitrator" from the API version loses the arbitrator setup, soooo.....

How to set up arbitrator on API version of Bisq?

**Comment by mrosseel** [comment]
@citkane great you're making progress :)
I  believe DevEnv needs to be adjusted anymore, just go to the UI of your arbitrator and use cmd+R to register a test arbitrator. The private key should be filled in automatically.

**Comment by citkane** [comment]
@mrosseel - yes, that was indeed the case when running the GUI from the Bisq-network version. The key was pre-filled.

This was not the case from the Bisq-API version. I tried the published dev private key, `6ac43ea1df2a290c1c8391736aa42e4339c5cb4f110ff0257a13b63211977b7a` but the app responded that the key was incorrect.

**Comment by mrosseel** [comment]
Very strange, the Bisq-API is essentially a wrapper around the normal Bisq app which additionally starts up the HTTP server to communicate with the API. This kind of difference is unexpected (and it has worked in the past otherwise how would I have tested the api ;).

Workaround: you can start your arbitrator from the bisq-network version and only run Alice/Bob from the API version

**Comment by citkane** [comment]
Tried the workaround already. Alice and Bob do not see the arbitrator.

I will go nuclear, make a fresh start and recompile everything then get back if problem persists.

**Comment by mrosseel** [comment]
Make sure everyone is started in REGTEST modus, and that they all point to the correct seednode port etc?

**Comment by citkane** [comment]
Yes - start seednode:
`java -jar seednode/target/SeedNode.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:2002 --nodePort=2002 --appName=bisq_seed_node_localhost_2002`

Start arbitrator:
`BISQ_API_PORT=4445 mvn exec:java -Dexec.mainClass="io.bisq.api.app.BisqApiWithUIMain" -Dexec.args="--baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost localhost --nodePort 4444 --useLocalhost true --appName Bisq-Regtest-Arbitrator --seedNodes=localhost:2002"`

I deleted both `~/.local/share/<appName>`s for fresh retry, but private key was still not pre-filled:

![regtest1](https://user-images.githubusercontent.com/998947/34117533-e44b2e8e-e413-11e7-9904-2fefa04daac9.jpg)

![regtest2](https://user-images.githubusercontent.com/998947/34117548-ecd11fb4-e413-11e7-8292-36c176205709.jpg)

Everyting else works - I can fund wallets,etc from bitcoin core. Will try the nuclear option now.

**Comment by citkane** [comment]
I have cleared and recompiled everything (all cloned from master) and report:

**Bisq-network:**

1. From 'clean' compile, arbitrator private key is not prefilled and default key `6ac43ea1df2a290c1c8391736aa42e4339c5cb4f110ff0257a13b63211977b7a` is not valid.
2. Compiled with modifications to DevEnv.java as described here: https://github.com/bisq-network/exchange/wiki/4.2.1.-How-to-use-Bisq-with-regtest-(advanced) prefills the private key and arbitrator registration succeeds.
`java -jar gui/target/shaded.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:4444 --nodePort=4444 --appName=Bisq-Regtest-Arbitrator`

3. Opening Alice and Bob GUI from Bisq-network works as expected and the arbitrator is available. 
`java -jar gui/target/shaded.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:3333 --nodePort=3333 --appName=Bisq-Regtest-Alice`
<>
`java -jar gui/target/shaded.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:2222 --nodePort=2222 --appName=Bisq-Regtest-Bob`

**Bisq-api**
1. From 'clean' compile, arbitrator private key is not prefilled and default key `6ac43ea1df2a290c1c8391736aa42e4339c5cb4f110ff0257a13b63211977b7a` is not valid.
`BISQ_API_PORT=4445 mvn exec:java -Dexec.mainClass="io.bisq.api.app.BisqApiWithUIMain" -Dexec.args="--baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost localhost --nodePort 4444 --useLocalhost true --appName Bisq-Regtest-Arbitrator --seedNodes=localhost:2002"`

2. DevEnv.java is not available in the repo, so this option is unavailable.
3. Arbitrator GUI is left open on the network, running from "Bisq-network". Verified to be working correctly due to (2,3) from above.
`java -jar gui/target/shaded.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:4444 --nodePort=4444 --appName=Bisq-Regtest-Arbitrator`

4. Gui clients for Bob and Alice function as expected from Bisq-api, except that the arbitrator is not available/visible.
`BISQ_API_PORT=3334 mvn exec:java -Dexec.mainClass="io.bisq.api.app.BisqApiWithUIMain" -Dexec.args="--baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost localhost --nodePort 3333 --useLocalhost true --appName Bisq-Regtest-Alice --seedNodes=localhost:2002"`
<>
`BISQ_API_PORT=4445 mvn exec:java -Dexec.mainClass="io.bisq.api.app.BisqApiWithUIMain" -Dexec.args="--baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost localhost --nodePort 4444 --useLocalhost true --appName Bisq-Regtest-Arbitrator --seedNodes=localhost:2002"`

It would appear to me that DevEnv.java needs to be included in the bisq-api for arbitrator registration to succeed. Any other workaround ideas?

**Comment by mrosseel** [comment]
just tested it locally and you are correct, regtest arbitrator + api is no longer working. I'll try to find a fix for that.

**Comment by mrosseel** [comment]
@citkane the issue has been fixed, could you please test and let me know if it worked?

* First of all, you will need to check out another repo for Bisq-exchange:
https://github.com/mrosseel/bisq-exchange.git
* Then just update the bisq-api repo.
* Add the parameter --useDevPriviligeKey to your startup params

**Comment by citkane** [comment]
I am having trouble compiling https://github.com/mrosseel/bisq-exchange.git. I tried using instructions:

1. https://github.com/mrosseel/bisq-exchange/blob/master/doc/build.md
2. https://github.com/bisq-network/exchange/blob/master/doc/build.md

with the result:

`[ERROR] Failed to execute goal on project common: Could not resolve dependencies for project io.bitsquare:common:jar:0.4.8: Could not find artifact org.bitcoinj:bitcoinj-core:jar:0.13.1.4 in sonatype-oss-snapshot (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]`

I have tried with clean maven repo, with/without bitcoinj, bisq inside/outside of bitcoinj dir. Always the same. I think maybe  https://github.com/mrosseel/bisq-exchange.git is looking for a different version of bitcoinj from https://github.com/bitsquare/bitcoinj.git?

**Comment by mrosseel** [comment]
Ah sorry, forgot to write that you need to switch to the 'addDevKeyParserOption' branch.

**Comment by citkane** [comment]
Nope....

Starting seedNode with:
`java -jar seednode/target/SeedNode.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:2002 --nodePort=2002 --appName=bisq_seed_node_localhost_2002 --useDevPrivilegeKey`

And API client with:
`BISQ_API_PORT=4445 mvn exec:java -Dexec.mainClass="io.bisq.api.app.BisqApiWithUIMain" -Dexec.args="--baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost localhost --nodePort 4444 --useLocalhost true --appName Bisq-Regtest-Arbitrator --seedNodes=localhost:2002 --useDevPrivilegeKey"`

But still no pre-filled key and default key is not valid.

**Comment by mrosseel** [comment]
only difference I see with my setup is that my arbitrator is not an API client, only Alice/Bob are API clients. Don't see immediately why that should be a problem, I'll test with your setup

**Comment by mrosseel** [comment]
just tested with your exact configuration and it works, after CMD+R the arbitrator key is pre-filled.
Make sure you did a git pull on bisq-api and that building succeeded. Let me know how it went!

**Comment by citkane** [comment]
I am 100% sure. I deleted all old directories, deleted old user files, new clone and compile:

**Network:**
```
cd bisq-network

git clone -b addDevKeyParserOption https://github.com/mrosseel/bisq-exchange.git ./

mvn clean package verify -DskipTests -Dmaven.javadoc.skip=true

java -jar seednode/target/SeedNode.jar --baseCurrencyNetwork=BTC_REGTEST --useLocalhost=true --myAddress=localhost:2002 --nodePort=2002 --appName=bisq_seed_node_localhost_2002 --useDevPrivilegeKey
```

**API:**
```
cd bisq-api

git clone https://github.com/mrosseel/bisq-api.git ./

mvn clean install

BISQ_API_PORT=4445 mvn exec:java -Dexec.mainClass="io.bisq.api.app.BisqApiWithUIMain" -Dexec.args="--baseCurrencyNetwork=BTC_REGTEST --bitcoinRegtestHost localhost --nodePort 4444 --useLocalhost true --appName Bisq-Regtest-Arbitrator --seedNodes=localhost:2002 --useDevPrivilegeKey"
```

**Comment by citkane** [comment]
> Add the parameter --useDevPriviligeKey to your startup params

I assume you meant at the above "--useDevPrivilegeKey" - the above threw an error at runtime. Maybe this is still wrong?

**Comment by mrosseel** [comment]
I'm reproducing your steps and will come back with my result

**Comment by mrosseel** [comment]
* I copy pasted your exact commands in fresh directories, and the example worked fine. 
* Then I cleaned my .m2/repository folder and it showed your behaviour.

Very strange, but a good hint on what's wrong ! Will continue investigating tomorrow morning.

**Comment by mrosseel** [comment]
@citkane just pushed a temp fix for the problem, please test! The API is now out-of-the-box configured for testing, if you want to use it on mainnet you need to point the Bisq-exchange dependency to the latest release. Will find a way to switch this later, for now this should work.

Steps:
- git pull on master of bisq-api
- don't use the --useDevPrivilegeKey anymore

**Comment by citkane** [comment]
Working :)
Thanks @mrosseel. 
I have put a step by step guide here: https://github.com/mrosseel/bisq-api/issues/4

Just to note, I am using you bisq-network fork, addDevKeyParserOption branch. This is because the Master branch on main is no longer launching a seed node with error:
`ERROR i.b.c.c.Encryption: JCE cannot authenticate the provider BC`

I know this has nothing to do with your API, and I will open the issue over there. I am just explaining why my guide is still pointing to your fork.

**Comment by mrosseel** [comment]
thx for the guide!
