### ISSUE TITLE
Headless mode: not all endpoints are working 

### ISSUE THREAD

**Issue by citkane** [mrosseel/bisq-api#20]
Following on from https://github.com/mrosseel/bisq-api/issues/13:

The following endpoints are still not working in headless mode from latest on `master`:

**offer_take**
```
http://localhost:3123/api/v1/offer_take?offer_id=1dfea1ab-e4f8-42d5-8d39-868fe620cfd2&payment_account_id=97f0ff19-3854-4a72-b459-d3ceeecddefb%20&amount=100000000

{
  "code": 500,
  "message": "Toolkit not initialized"
}
```

**offer_cancel**
```
http://localhost:3113/api/v1/offer_cancel?offer_id=53fc4cf3-cbc5-463c-bbac-3061eeda4349

{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID d6dd0e51c6d6902a)."
}
```

**payment_started**
```
http://localhost:3113/api/v1/payment_started?trade_id=ba3061d3-2e0b-4857-9a59-ed0006c61d66

{
  "code": 500,
  "message": "Toolkit not initialized"
}
```

**payment_received**
```
http://localhost:3123/api/v1/payment_received?trade_id=ba3061d3-2e0b-4857-9a59-ed0006c61d66

{
  "code": 500,
  "message": "Toolkit not initialized"
}
```

**move_funds_to_bisq_wallet**
```
http://localhost:3113/api/v1/move_funds_to_bisq_wallet?trade_id=ba3061d3-2e0b-4857-9a59-ed0006c61d66

{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID 8c0aa41da39bcd2a)."
}
```

**All endpoints are working in GUI mode, all other listed issues from https://github.com/mrosseel/bisq-api/issues/13 tested and working in headless mode.**

**Comment by mrosseel** [comment]
could you retest? Offer_take and offer_cancel was tested by me and work.
There's a guy working on the integration tests (see #10 ) so hopefully these kind of regressions will be automated soon.

**Comment by citkane** [comment]
I retested in headless on my laptop and all the endpoints appear to be working. However, when running on a server,  new issue https://github.com/mrosseel/bisq-api/issues/22 happens.

**Comment by mrosseel** [comment]
OK, I answered in #22, lets close this issue as it is essentially solved, and the remaining bugs are described in #22.
