### ISSUE TITLE
Slow trade statistics updates: bug?

### ISSUE THREAD

**Issue by meapistol** [mrosseel/bisq-api#3]
The Bisq-api updates trade statistics very slowly. I have run it side by side with the normal Bisq. However Spread is up to date.

**Comment by mrosseel** [comment]
the Bisq-api is just a wrapper on top of normal Bisq, and nothing tradestatistics related should have been touched. 
* Did you check that both were connected to the same seednode? 
* the API uses an older release, and I do think Manfred improved tradestatistics in 0.6.3, I'll update the dependency report on this ticket when done.

**Comment by mrosseel** [comment]
this behaviour could not be reproduced, and much has changed since the time of this report.
If you still see this behaviour in the latest api version feel free to reopen this ticket!
