### ISSUE TITLE
Create Payment Accounts or Wallet Address

### ISSUE THREAD

**Issue by cristin** [mrosseel/bisq-api#34]
Hello,

I managed to setup the Bisq API on docker, or I think is running ok. First I tried the latest version but the Integration Tests were failing. So I check out the commit 27ee2f81afceeb49fa69bad9e3a42e12a6ed7e18 and the integration tests passed.

I'm trying to create a new Payment account and new wallet address for users (alice & bob) in order to create an offer. 

Wallet Address 
The create wallet endpoint seems to work, it returns a wallet address but when I use the GET endpoint to get the address the response is empty.

Payment Accounts
The create endpoint keeps returning  "message": "Unable to process JSON".  Bellow is the JSON used to create a payment account:
`{
  "paymentMethod": "National bank transfer",
  "selectedTradeCurrency": "EUR",
  "tradeCurrencies": [
    "BTC"
  ]
}`

Could you please help me understand where I'm doing something wrong? 

Also, does the API work at this point without the UI? Or you still need a UI opened and configured in order for the API to work? 

Thank you!

**Comment by blabno** [comment]
We currently only support SEPA
`curl -X POST -s "http://localhost:$ALICE_PORT/api/v1/payment-accounts" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"paymentMethod\": \"SEPA\", \"selectedTradeCurrency\": \"EUR\", \"tradeCurrencies\": [ \"EUR\" ],\"accountName\":\"SEPA EUR\",\"countryCode\":\"PL\",\"holderName\":\"Alice\",\"bic\":\"YJGSBIF70Q7\",\"iban\":\"EE875639607137003809\"}"`

```
{
  "paymentMethod": "SEPA",
  "selectedTradeCurrency": "EUR",
  "tradeCurrencies": [
    "EUR"
  ],
  "accountName": "SEPA EUR",
  "countryCode": "PL",
  "holderName": "Alice",
  "bic": "YJGSBIF70Q7",
  "iban": "EE875639607137003809"
}
```

**Comment by blabno** [comment]
Tomorrow I'm going to add all other supported payment methods.

**Comment by cristin** [comment]
Thank you @blabno ! I manged to find the sh files in support and saw there the complete JSON to create payment accounts. I also managed to create offers and to take an offer. Now I just to have to figure out how to complete the process. 

What other payment methods will you add? 

Is there a way to start a bisq-api instance for a specific user for which I know the wallet address?

Thank you!

**Comment by blabno** [comment]
@cbeams I've added all payment methods: https://github.com/mrosseel/bisq-api/pull/37

**Comment by blabno** [comment]
@cristin #37 got merged in. Now all payment methods are supported.
