### ISSUE TITLE
Does the API support other currencies?

### ISSUE THREAD

**Issue by cristin** [mrosseel/bisq-api#39]
Hi,

Does the API support opening an instance of other wallets then Bitcoin? Am I right in thinking that if I want ETH I should also put up a ETH blockchain and link that to bisq-seednode and bisq-api in the docker config files?

Thank you!

**Comment by mrosseel** [comment]
Bisq only supports a btc wallet, so you either need an ethereum full node
or (easier) check using a block explorer

**Comment by mrosseel** [comment]
That docker image seems to be running a full node yes, haven't checked it out further.

When you use the DEV docker images, all ports should be correct. 
Just to be clear: Bisq doesn't know anything about your ETH full node, you will have to access that in your program. I do suggest starting with an online blockexplorer though, will be easier to get working and afterwards you can still switch if needed.

**Comment by mrosseel** [comment]
closing this, unless you have any more questions on this
