### ISSUE TITLE
PaymentAccount is not valid for offer

### ISSUE THREAD

**Issue by citkane** [mrosseel/bisq-api#5]
I have set up a regtest environment as per here: https://github.com/mrosseel/bisq-api/issues/4
and also tested with the latest seedNode as per here: https://github.com/bisq-network/exchange/issues/1114#issuecomment-353571921

I am experiencing difficulty initiating a new offer as per the api calls below:
```
http://localhost:2223/api/v1/offer_make?market_pair=xmr_btc&payment_account_id=a16f4169-12f8-48f4-823c-eb35a8e51833&direction=BUY&amount=100000000&min_amount=50000000&fixed=fixed&fixed_price=600

http://localhost:2223/api/v1/offer_make?market_pair=btc_xmr&payment_account_id=a16f4169-12f8-48f4-823c-eb35a8e51833&direction=BUY&amount=100000000&min_amount=50000000&fixed=fixed&fixed_price=600
```
I am trying the market_pair `xmr_btc` and `btc_xmr`, but the response is always:
```
500
"There is no valid market pair called: xmr_btc"
```
or
```
500
"There is no valid market pair called: btc_xmr"
```
I have tried this with various options, btc_euro, euro_btc, etc - but always a `500` response.

**Would you please help identify if there is a regression in the API, or am I doing something wrong?**

Also, could you clarify workflow logic around the following:

- At the endpoints `offer_list` and `offer_detail` i cannot see a way to determine the acceptable payment methods for an offer. Is there a facility for this?

- Can the API identify my own "onion address" ("localhost:port" for regtest) so that I can compare it against an offer's "offerer" to determine if a trade is my own?

**Comment by mrosseel** [comment]
thanks for the report, I'll check it out as soon as possible! xmr_btc should be correct, strange.

**Comment by mrosseel** [comment]
should be fixed in:
https://github.com/mrosseel/bisq-api/commit/71a00744f59c67d8249c202bef4615d1e45ffd96

**Comment by citkane** [comment]
I have pulled latest from Master and recompiled. The behaviour is different but not successful.

Given the API call:
```
http://localhost:3103/api/v1/offer_make?market_pair=xmr_btc&payment_account_id=a16f4169-12f8-48f4-823c-eb35a8e51833&direction=BUY&amount=100000000&min_amount=100000000&fixed=fixed&fixed_price=600
```
with the XMR account :
```
  {
    "payment_account_id": "a16f4169-12f8-48f4-823c-eb35a8e51833",
    "created": 1514571852100,
    "account_name": "XMR: 1234",
    "trade_currencies": [
      "XMR"
    ],
    "paymentAccountPayload": "CryptoCurrencyAccountPayload(address=1234)",
    "payment_method_details": {
      "contractData": {
        "paymentMethodId": "BLOCK_CHAINS",
        "id": "a16f4169-12f8-48f4-823c-eb35a8e51833",
        "maxTradePeriod": -1,
        "excludeFromJsonDataMap": {
          "salt": "33033e36214cdfab99b62d0edccf1b1c0d8cd573f803ac36a4868edd857fadc3"
        },
        "address": "1234",
        "ageWitnessInputData": "QkxPQ0tfQ0hBSU5TMTIzNA==",
        "paymentDetails": "Receivers altcoin address: 1234",
        "paymentDetailsForTradePopup": "Receivers altcoin address: 1234",
        "salt": "MwM+NiFM36uZti0O3M8bHA2M1XP4A6w2pIaO3YV/rcM="
      }
    }
  }
```
the API responds:
```
{
  "code": 500,
  "message": "PaymentAccount is not valid for offer"
}
```
I have tried both `BUY` and `SELL` directions and also `btc_euro` market pair (and fiat account id) with the same response result.

**Comment by mrosseel** [comment]
The latest commit (e662a3f) fixes this bug, I could create an offer using your http call.
Do note that as of now, marketpair strings are uppercase, so please use XMR_BTC, LTC_BTC etc.

Let me know if I can close this ticket. If you find other issues please open another ticket, thx.

**Comment by citkane** [comment]
The latest commit fails to build for me with:
```
org.junit.ComparisonFailure: expected:<[left_right]> but was:<[LEFT_RIGHT]>
```
Log: [apibuildfail.txt](https://github.com/mrosseel/bisq-api/files/1615842/apibuildfail.txt)

**Comment by mrosseel** [comment]
I have more unit tests than I thought :). Latest commit fixes this error.
In the future if unit tests fail just build with -DskipTests, but thx for the report!

**Comment by citkane** [comment]
Working, thanks :)

This issue can be closed.
