### ISSUE TITLE
"offer_take" for direction BUY not interpreting "amount" parameter correctly

### ISSUE THREAD

**Issue by citkane** [mrosseel/bisq-api#7]
Given the following offer detail:
```
{
  "offer_id": "CB4Nac-822d3e5c-2c95-457f-aa70-e2450c9d4317-062",
  "direction": "BUY",
  "state": "UNKNOWN",
  "created": 1515149623950,
  "arbitrators": [
    "localhost:3302"
  ],
  "offerer": "localhost:3202",
  "btc_amount": "0.1875",
  "min_btc_amount": "0.1",
  "other_amount": "13486.28",
  "other_currency": "EUR",
  "price_detail": {
    "use_market_price": true,
    "market_price_margin": 0
  }
}
```
and the following API call:
```
http://localhost:3103/api/v1/offer_take?offer_id=CB4Nac-822d3e5c-2c95-457f-aa70-e2450c9d4317-062&payment_account_id=ccd32497-5100-4cc9-99b9-94fa36150368&amount=10000000
```
the API responds:
```
200
true
```
but the offer is not processed in BISQ. It is possible to re-submit the call indefinitely and get the same `200:true` response.

If the `amount` parameter is reduced by a factor of 10 (10,000,000 to 1,000,000) the API call succeeds and the offer is processed, but shows in the GUI with the incorrect value of 0.01BTC instead of 0.1BTC.

This is only true for a `BUY` direction offer and the `SELL` direction offers would appear to function as expected.

**Comment by mrosseel** [comment]
thanks for the report, I will have a look and try to replicate. If you still have the offer_create url feel free to post that too, so I'm sure that everything is the same.

**Comment by citkane** [comment]
Thanks:
`offer_create` is 404:not found and `offer_make` is still the same invalid market pair as per here:https://github.com/mrosseel/bisq-api/issues/5. The url calls are described in this issue.

**Comment by mrosseel** [comment]
* If offer_create is not working, how did you make the offer, via the UI?
* #5 should be fixed already, I did notice I forgot to comment in the issue that it was fixed, done now.

**Comment by citkane** [comment]
Yes, I created the offer through the UI. Thanks - I will recompile and test the offer creation through API. Have you changed the endpoint from `offer_make` to `offer_create`?

**Comment by Quenos** [comment]
Have same issues as @citkane citkane
Is the fix for #5 merged with the master? Last change was 8 days ago.

**Comment by mrosseel** [comment]
Fix for #5 should be in [this commit in master](https://github.com/mrosseel/bisq-api/commit/71a00744f59c67d8249c202bef4615d1e45ffd96).
Today I have time to retest everything and fix outstanding issues.

**Comment by citkane** [comment]
I have pulled master for #5 / https://github.com/mrosseel/bisq-api/commit/71a00744f59c67d8249c202bef4615d1e45ffd96 and recompiled with the following result: https://github.com/mrosseel/bisq-api/issues/5#issuecomment-355969886

**Comment by mrosseel** [comment]
0.6.3 has some fixes for InsufficientMoneyException errors, to exclude those the api will first be made to depend on that version (see #9 ) and the API code compared to that new code. 
Not saying it was a bug in bisq, but let's rule that out and have the new version of bisq to depend on in one go!

**Comment by mrosseel** [comment]
There was a problem with the calculation of the needed funds for the BUY direction, now fixed

**Comment by citkane** [comment]
I confirm that this issue is fixed by https://github.com/mrosseel/bisq-api/commit/abb6b68eb4abd61928a39a2184a3f9740cf26956
