### ISSUE TITLE
Init Docker instance with pre-defined configuration file

### ISSUE THREAD

**Issue by cristin** [mrosseel/bisq-api#77]
Hi,

Is it feasible to start a bisq instance with a pre-defined configuration file? For example, if I have all the information for a specific user (name, wallet address, currency), I first create the configuration files and then start the bisq api instance based on that configuration files?

Thank you!

**Comment by mrosseel** [comment]
In short: yes
Long answer: it depends a bit how you start the application. If you use the docker containers it might need some tweaking. If you start it as pure java, then you can just pass the appname of your choice. The appname maps directly to a directory name,  and if there is an existing directory for this appname bisq will read what's there. 

Practical: the easiest way is to start a GUI bisq (api or regular) and configure your payment accounts, wallets, ... . Then go to Account > Backup > Open directory => this is the location of your application data directory. If you start the api with the same appname as the GUI, it will point to the same dir.

**Comment by cristin** [comment]
Yap, I found on my local machine the location of the applications data directory. I was wondering if there is any way to generate the data directory programmatically? More exactly the wallets files. So that I can open a bisq instance for a specific wallet without using the UI

**Comment by mrosseel** [comment]
There are API endpoints to create a payment method, get wallet addresses etc. 
So in theory you should be able to create everything programatically.
If you find anything missing let us know!

**Comment by cristin** [comment]
I don't know exactly if is missing or I'm just not approaching this right. From the API I see only an endpoint to create a default bitcoin wallet address, I don't see any way of adding an existing BTC wallet address.

What I want to achieve is to open a bisq API instance from scratch, without any configurations done in the UI,  for an existing wallet address that I have.

Also, are altcoins accounts supported?

**Comment by cristin** [comment]
About, Altcoin I just found PR #52 and if I understand correctly the api supports adding altcoin accounts. I just need to figure out how to use them. 

The 1st questions, opening a bisq api instance from scratch for an existing wallet address still exists.

**Comment by cristin** [comment]
Ok, I managed to use the API to create an Altcoin payment wallet for LTC. :)

The 1st questions, opening a bisq api instance from scratch for an existing wallet address still exists.

**Comment by mrosseel** [comment]
Regarding the existing wallet address: 
* bisq wallets can be recreated using their seed words, there isn't an API endpoint for that at the moment
* just creating the wallet with one private key would not work, the wallet needs to generate new addresses
* even if you create it with seed words you use in another wallet, there's the risk that you start spending from addresses which bisq has used for trade deposits etc so this will not end well I think

Alternatives:
* trades can be funded by your external wallet 
* bisq generated addresses can be queried by the API

**Comment by blabno** [comment]
You can mount volume to your existing Bisq data directory:
```
docker run -it -v ~/.local/share/Bisq:/root/.local/share/Bisq -p 8080:8080 bisq-api
```

We could implement import/export of some data to a file but without AddressEntries.
